---
apiVersion: v1
kind: ConfigMap # best practice to keep CM in another file
metadata:
   name: nwapp-cm 
   labels:
      app: northwind

data:
   DB_USER: root
   DB_HOST: nwdb-svc.nw-ns.svc.cluster.local

---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: nwapp-deploy
   labels:
      app: northwind

spec:
   replicas: 2
   selector:
      matchLabels:
         app: nwapp-pod
   template:
      metadata:
         name: nwapp-pod 
         labels:
            app: nwapp-pod
      spec:
         containers:
         - name: nwapp-container
           image: happybits/nwapp:v3
           imagePullPolicy: IfNotPresent
           env:
           - name: DB_USER
             valueFrom:
                configMapKeyRef:
                   name: nwapp-cm 
                   key: DB_USER
           - name: DB_HOST
             valueFrom:
                configMapKeyRef:
                   name: nwapp-cm 
                   key: DB_HOST
           - name: DB_PASSWORD 
             valueFrom:
                secretKeyRef:
                   name: nwdb-secret
                   key: MYSQL_ROOT_PASSWORD
           - name: INSTANCE_IP_ADDRESS 
             valueFrom:
                fieldRef:
                   fieldPath: status.podIP
           ports:
           - name: nwapp-port
             containerPort: 3000
           livenessProbe:
              initialDelaySeconds: 5
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 3
              httpGet:
                 path: /health
                 port: nwapp-port

---
apiVersion: v1
kind: Service 
metadata:
  name: nwapp-svc
  labels:
    app: northwind
spec:
  type: ClusterIP
  selector:
    app: nwapp-pod  # this should be same as selector in Deployment

  ports:
  - name: app-port
    port: 8080       # ingress port
    targetPort: 3000 # can just put nwapp-port. Defined above
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nwapp-ing
  labels:
    app: northwind
  annotations:
    kubernetes.io/ingress.class: "nginx" # ingress name
spec:
  rules:
  - host: "nwapp.157.230.193.185.nip.io" #ip is from nginx ingress load balancer. this needs to be a hostname. hence use nip.io to fake one
    http:
      paths:
      - path: /
        backend:
          serviceName: nwapp-svc
          servicePort: 8080

