---
apiVersion: v1
kind: Secret   # best practice to put secret in another file
metadata:
  name: nwdb-secret
  labels:
    app: northwind

data:
  MYSQL_ROOT_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwdb-deploy
  #namespace: nwapp     dont define namespace here. namespace may change. declare name space outside at cmd
  labels:
    app: northwind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: northwind-pod
  template: # pod template
    metadata:
      name: nwdb-pod
      labels:
        app: northwind-pod
    spec:
      volumes:
      - name: mysql-vol
        persistentVolumeClaim:
          claimName: nwdb-pvc   # must be same as your persistentVol name
      
      # only for digital ocean. to clear some unwanted data
      initContainers:
      - name: scrub
        volumeMounts:
          - name: mysql-vol
            mountPath: /scrub
          image: busybox
          command:
            - /bin/sh
            - -c
            - "test -e /scrub && rm -rf /scrub/..?* /scrub/.[!.]* /scrub/*  && test -z \"$(ls -A /scrub)\" || exit 1"
          imagePullPolicy: IfNotPresent

      containers:
      - name: nwdb-container
        image: happybits/nwdb:v3
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: # must be from same namespace
            secretKeyRef: 
              name: nwdb-secret # from metadata:name in secret
              key: MYSQL_ROOT_PASSWORD  # from data in secret
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
          exec:
            command:
            - bash
            - -c
            - "mysqladmin ping -uroot -p${MYSQL_ROOT_PASSWORD} || exit 1" #$MYSQL_ROOT_PASSWORD is from the env var set in the container by the env in spec


        ports:
        - name: mysql-port
          containerPort: 3306

        volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: nwdb-svc
  labels:
    app: northwind
spec:
  type: ClusterIP
  selector:
    app: northwind-pod  # this should be same as selector in Deployment

  ports:
  - name: db-port
    port: 3306       # ingress port
    targetPort: 3306 # can just put mysql-port also. port defined above
