---
apiVersion: v1
kind: Namespace
metadata:
  name: myns
  labels:
    dept: engineering
---
apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
  namespace: myns
  labels:
    dept: engineering
    app: fortune
spec:
  containers:
  - name: fortune-container
    image: happybits/fortune:v2
    imagePullPolicy: IfNotPresent
    env:
    - name: APP_PORT
      value: "8080"        # setting container's exposed port. env var in container app
    # this is the pod's exposed port
    ports:
    - name: http-port
      containerPort: 5000   # pod's exposed port
