---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
   name: wpapp-ing
   labels:
      app: wordpress
   annotations:
      kubernetes.io/ingress.class: "nginx"

spec:
   rules:
   - host: "wpapp.167.172.6.213.nip.io"
     http:
        paths:
        - path: /
          backend:
             serviceName: wpapp-svc
             servicePort: 80

